# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    build_dir: /android/
    working_directory: ~/Documents/projects/umbrella_temp/basic_algorithm/umbrella_white-label
       docker:
          - image: circleci/android:api-28-alpha
                - run:
                   name: Chmod permissions
                   command: sudo chmod +x ./gradlew
                - run:
                    name: Download Dependencies
                    command: ./gradlew androidDependencies
                - run:
                    name: Run Unit Tests
                    command: ./gradlew test
                - run:
                    name: Run Linters
                    command: ./gradlew check
                - run:
                    name: Build
                    command: ./gradlew assemble